const Alert = require('../models/Alert');

class AlertService {
  // Create a quantity discrepancy alert
  static async createQuantityDiscrepancyAlert(transferData, receiptData) {
    try {
      const {
        transferId,
        itemName,
        expectedQuantity,
        receivedQuantity,
        quantityDifference,
        discrepancyPercentage,
        fromStorageSite,
        toStorageSite,
        transferredBy,
        receivedBy
      } = transferData;

      const alertData = {
        type: 'quantity_discrepancy',
        category: 'inventory',
        severity: discrepancyPercentage > 10 ? 'high' : 'medium',
        title: `Quantity Discrepancy in Transfer`,
        message: `Transfer of ${itemName} shows quantity discrepancy. Expected: ${expectedQuantity}, Received: ${receivedQuantity} (${discrepancyPercentage.toFixed(1)}% difference)`,
        details: {
          transferId,
          itemName,
          expectedQuantity,
          receivedQuantity,
          quantityDifference,
          discrepancyPercentage,
          fromStorageSite: fromStorageSite.name,
          toStorageSite: toStorageSite.name,
          transferredBy: `${transferredBy.firstName} ${transferredBy.lastName}`,
          receivedBy: `${receivedBy.firstName} ${receivedBy.lastName}`
        },
        status: 'active',
        priority: discrepancyPercentage > 10 ? 'high' : 'medium',
        assignedTo: [transferredBy._id, receivedBy._id], // Alert both managers
        createdBy: receivedBy._id,
        metadata: {
          transferId,
          alertType: 'quantity_discrepancy',
          autoGenerated: true
        }
      };

      const alert = new Alert(alertData);
      await alert.save();

      console.log(`Quantity discrepancy alert created: ${alert._id}`);
      return alert;
    } catch (error) {
      console.error('Error creating quantity discrepancy alert:', error);
      throw error;
    }
  }

  // Create a transfer completion alert
  static async createTransferCompletionAlert(transferData) {
    try {
      const {
        transferId,
        itemName,
        quantity,
        fromStorageSite,
        toStorageSite,
        transferredBy,
        receivedBy,
        vehicle
      } = transferData;

      const alertData = {
        type: 'transfer_completed',
        category: 'inventory',
        severity: 'low',
        title: `Transfer Completed Successfully`,
        message: `Transfer of ${quantity} ${itemName} from ${fromStorageSite.name} to ${toStorageSite.name} has been completed successfully.`,
        details: {
          transferId,
          itemName,
          quantity,
          fromStorageSite: fromStorageSite.name,
          toStorageSite: toStorageSite.name,
          transferredBy: `${transferredBy.firstName} ${transferredBy.lastName}`,
          receivedBy: `${receivedBy.firstName} ${receivedBy.lastName}`,
          vehicle: vehicle.vehicleNumber
        },
        status: 'active',
        priority: 'low',
        assignedTo: [transferredBy._id], // Notify source manager
        createdBy: receivedBy._id,
        metadata: {
          transferId,
          alertType: 'transfer_completed',
          autoGenerated: true
        }
      };

      const alert = new Alert(alertData);
      await alert.save();

      console.log(`Transfer completion alert created: ${alert._id}`);
      return alert;
    } catch (error) {
      console.error('Error creating transfer completion alert:', error);
      throw error;
    }
  }

  // Create a vehicle trip completion alert
  static async createVehicleTripAlert(vehicleData, transferData) {
    try {
      const {
        vehicleId,
        vehicleNumber,
        dailyTrips,
        totalTrips,
        tripDate
      } = vehicleData;

      const {
        transferId,
        itemName,
        quantity,
        fromStorageSite,
        toStorageSite
      } = transferData;

      const alertData = {
        type: 'vehicle_trip_completed',
        category: 'vehicle',
        severity: 'low',
        title: `Vehicle Trip Completed`,
        message: `Vehicle ${vehicleNumber} completed trip #${dailyTrips} for the day. Total trips: ${totalTrips}`,
        details: {
          vehicleId,
          vehicleNumber,
          dailyTrips,
          totalTrips,
          tripDate,
          transferId,
          itemName,
          quantity,
          fromStorageSite: fromStorageSite.name,
          toStorageSite: toStorageSite.name
        },
        status: 'active',
        priority: 'low',
        assignedTo: [], // Could be assigned to fleet manager
        createdBy: transferData.receivedBy._id,
        metadata: {
          vehicleId,
          transferId,
          alertType: 'vehicle_trip_completed',
          autoGenerated: true
        }
      };

      const alert = new Alert(alertData);
      await alert.save();

      console.log(`Vehicle trip alert created: ${alert._id}`);
      return alert;
    } catch (error) {
      console.error('Error creating vehicle trip alert:', error);
      throw error;
    }
  }

  // Create a low stock alert after transfer
  static async createLowStockAlertAfterTransfer(inventoryItem) {
    try {
      const {
        _id: itemId,
        itemName,
        currentStock,
        minimumStock,
        storageSite
      } = inventoryItem;

      if (currentStock <= minimumStock) {
        const alertData = {
          type: 'low_stock',
          category: 'inventory',
          severity: currentStock === 0 ? 'high' : 'medium',
          title: `Low Stock Alert: ${itemName}`,
          message: `${itemName} is running low. Current stock: ${currentStock}, Minimum required: ${minimumStock}`,
          details: {
            itemId,
            itemName,
            currentStock,
            minimumStock,
            storageSite: storageSite.name,
            stockPercentage: (currentStock / minimumStock) * 100
          },
          status: 'active',
          priority: currentStock === 0 ? 'high' : 'medium',
          assignedTo: [], // Will be assigned to storage site managers
          createdBy: null, // System generated
          metadata: {
            itemId,
            alertType: 'low_stock',
            autoGenerated: true
          }
        };

        const alert = new Alert(alertData);
        await alert.save();

        console.log(`Low stock alert created: ${alert._id}`);
        return alert;
      }
    } catch (error) {
      console.error('Error creating low stock alert:', error);
      throw error;
    }
  }

  // Get alerts for a specific user
  static async getUserAlerts(userId, params = {}) {
    try {
      const {
        page = 1,
        limit = 20,
        status = 'active',
        category,
        severity
      } = params;

      const query = {
        $or: [
          { assignedTo: userId },
          { createdBy: userId }
        ]
      };

      if (status) {
        query.status = status;
      }

      if (category) {
        query.category = category;
      }

      if (severity) {
        query.severity = severity;
      }

      const alerts = await Alert.find(query)
        .sort({ createdAt: -1 })
        .limit(parseInt(limit))
        .skip((parseInt(page) - 1) * parseInt(limit))
        .populate('assignedTo', 'firstName lastName email')
        .populate('createdBy', 'firstName lastName email');

      const totalCount = await Alert.countDocuments(query);

      return {
        alerts,
        pagination: {
          currentPage: parseInt(page),
          totalPages: Math.ceil(totalCount / parseInt(limit)),
          totalCount,
          hasNext: parseInt(page) * parseInt(limit) < totalCount,
          hasPrev: parseInt(page) > 1
        }
      };
    } catch (error) {
      console.error('Error getting user alerts:', error);
      throw error;
    }
  }

  // Mark alert as resolved
  static async resolveAlert(alertId, resolvedBy, resolutionNotes) {
    try {
      const alert = await Alert.findById(alertId);
      if (!alert) {
        throw new Error('Alert not found');
      }

      alert.status = 'resolved';
      alert.resolvedBy = resolvedBy;
      alert.resolvedAt = new Date();
      alert.resolutionNotes = resolutionNotes;

      await alert.save();
      return alert;
    } catch (error) {
      console.error('Error resolving alert:', error);
      throw error;
    }
  }
}

module.exports = AlertService;
